---
title: "Bachelor"
author: "Lasse Hansen"
date: "August 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
p_load(tidyverse)
setwd("~/Desktop/Bachelor/Autobiographic/Depression2")
```


#Load txt files from ELAN, add filename and headers
```{r}
ELANload = function(file){
  df = read.delim(file, header = F)
  df$File = as.factor(file)
  return(df)
}
```

```{r}
#20 controls
#35 depression
#20 depression 2


#creating a list of all the .csv files in all the folders
file.list <- list.files(pattern = '*.txt', full.names = F)

file.list
#reading all the csv files in the file.list
df.list <- lapply(file.list, ELANload)
#turning into a data frame
df <- bind_rows(df.list)


names(df)[1] <- "TimeStart"
names(df)[2] <- "StartSec"
names(df)[3] <- "TimeStop"
names(df)[4] <- "StopSec"
names(df)[5] <- "Explanation"


df$TimeStart = substring(df$TimeStart, 2)
df$TimeStart = gsub('.{2}$', '', df$TimeStart)
df$TimeStart = paste("(", df$TimeStart, sep = "") 
df$TimeStart = paste(df$TimeStart, ")", sep = "")


df$TimeStop = substring(df$TimeStop, 2)
df$TimeStop = gsub('.{2}$', '', df$TimeStop)
df$TimeStop = paste("(", df$TimeStop, sep = "") 
df$TimeStop = paste(df$TimeStop, ")", sep = "")

df$Length = df$StopSec-df$StartSec

df = subset(df, Length > 1)

df$StartSec = NULL
df$StopSec = NULL
df$Length = NULL


df <- df[c(1,3,2,4)]

write.csv(df, file = 'controls.csv')


```

